apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rds-autoscaler.fullname" . }}
  labels:
    {{- include "rds-autoscaler.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rds-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rds-autoscaler.fullname" . }}
